module.exports = {
  FETCH_MOVIES: 'FETCH_MOVIES',
  FIND_MOVIE: 'FIND_MOVIE',
  SEARCH_MOVIE: 'SEARCH_MOVIE',
  ADD_MOVIE: 'ADD_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  UPDATE_MOVIE: 'UPDATE_MOVIE'
};
