export default {
    FETCH_MOVIES : 'FETCH_MOVIES',
    FIND_MOVIE : 'FIND_MOVIE',
    SEARCH_MOVIES : 'SEARCH_MOVIES',
    ADD_MOVIE : 'ADD_MOVIE',
    DELETE_MOVIE : 'DELETE_MOVIE',
    UPDATE_MOVIE : 'UPDATE_MOVIE'
}